class Products {
  static final List<Map<String, dynamic>> all_products = [
    {
      'id': 1,
      'name': 'Item 1',
      'image': ['assets/images/item1.png'], //takes in a list of images
      'new_price': 29.99,
      'old_price': 49.99,
      'category': 'men',
      //   also include timestamp
    },
    {
      'id': 2,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'women',
      'image': ['assets/images/p2_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 3,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'men',
      'image': ['assets/images/p3_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 4,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'mens',
      'image': ['assets/images/p4_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 5,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p5_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 6,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p6_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 7,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'mens',
      'image': ['assets/images/p4_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 8,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'mens',
      'image': ['assets/images/p4_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 9,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p6_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 10,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p5_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 11,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p6_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 12,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p5_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 13,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p6_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
    {
      'id': 14,
      'name': 'Striped Flutter Sleeve Overlap Colloa',
      'category': 'kids',
      'image': ['assets/images/p5_img.jpg'],
      'new_price': 50.0,
      'old_price': 80.5,
    },
  ];
}
